version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - auto-pue-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - auto-pue-network

  backend:
    build:
      context: ./src/backend
      dockerfile: ../../.docker/backend/Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
      - "9229:9229"   # Debugger port
    volumes:
      - ./src/backend:/app
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mydatabase
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - auto-pue-network

  scan:
    build:
      context: ./src/scan
      dockerfile: ../../.docker/scan/Dockerfile
    container_name: scan
    ports:
      - "3002:3002"
    volumes:
      - ./src/scan:/app
    environment:
      MONGODB_URI: mongodb://mongodb:27017/mydatabase
    depends_on:
      - mongodb
    networks:
      - auto-pue-network

  cron:
    build:
      context: ./src/cron
      dockerfile: ../../.docker/cron/Dockerfile
    container_name: cron
    ports:
      - "3003:3003"
    volumes:
      - ./src/cron:/app
    environment:
      MONGODB_URI: mongodb://mongodb:27017/mydatabase
    depends_on:
      - mongodb
      - redis
    networks:
      - auto-pue-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - auto-pue-network

  frontend:
    build:
      context: ./src/frontend
      dockerfile: ../../.docker/frontend/Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"
    volumes:
      - ./src/frontend:/app
    depends_on:
      - backend
      - scan
      - cron
    networks:
      - auto-pue-network

volumes:
  mongo-data:

networks:
  auto-pue-network:
    driver: bridge
