name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # Csak a 'main' ágra történő push indítja el a deploy folyamatot

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          GIT_BRANCH: main
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
        run: |
          sudo apt-get update && sudo apt-get install -y openssh-client
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          echo "SSH key details:"
          ls -la ~/.ssh/
          ssh-add -l  # Ellenőrizni, hogy a kulcs betöltődött-e az SSH agent-be
          ssh -vvv ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'SSH connection successful'"
          ssh $SSH_USER@$SSH_HOST "
          cd /var/www/html &&
          git reset --hard &&
          git pull origin $GIT_BRANCH --force &&
          chmod -R 777 . &&
          bash /var/www/html/docker-compose-up-stg.sh &&
          yes | sudo docker system prune -a --volumes
          "
