name: Deploy to Server

on:
  push:
    branches:
      - main  # Csak a 'main' ágra történő push indítja el a deploy folyamatot

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Client and Setup SSH Agent
        run: |
          sudo apt-get update && sudo apt-get install -y openssh-client
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Debug SSH Connection
        run: |
          ssh -v ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'SSH connection successful'"

      - name: Deploy to Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          GIT_BRANCH: main
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
        run: |
          ssh $SSH_USER@$SSH_HOST "
          cd /var/www/html &&
          git pull origin $GIT_BRANCH &&
          bash docker-compose-up.sh &&
          echo $SUDO_PASSWORD | sudo -S bash update-script.sh &&
          yes | sudo docker system prune -a --volumes
          "
